# build image
services:
  web:
    build: .
    # image: ghcr.io/3kmfi6hp/argo-airport-paas:main
    ports:
      - "8080:3000"
    # volumes:
    #   - ./entrypoint.sh:/app/entrypoint.sh:ro
    #   - ./server.js:/app/server.js:ro
    # use .env file
    env_file:
      - .env
  web-2:
    build: .
    # image: ghcr.io/3kmfi6hp/argo-airport-paas:main
    ports:
      - "81:3000"
    # volumes:
    #   - ./entrypoint.sh:/app/entrypoint.sh:ro
    #   - ./server.js:/app/server.js:ro
    # use .env file
    # env_file:
    #   - .env
  web-build:
    build: 
      context: .
      dockerfile: Dockerfile.build
    # image: ghcr.io/3kmfi6hp/argo-airport-paas:main
    ports:
      - "82:3000"
    # volumes:
    #   - ./entrypoint.sh:/app/entrypoint.sh:ro
    #   - ./server.js:/app/server.js:ro
    # use .env file
    # env_file:
    #   - .env
  web-build-2:
    build: 
      context: .
      dockerfile: Dockerfile.build
    # image: ghcr.io/3kmfi6hp/argo-airport-paas:main
    ports:
      - "83:3000"
    # volumes:
    #   - ./entrypoint.sh:/app/entrypoint.sh:ro
    #   - ./server.js:/app/server.js:ro
    # use .env file
    env_file:
      - .env
  web-debian:
    build: 
      context: .
      dockerfile: Dockerfile.debian
    # image: ghcr.io/3kmfi6hp/argo-airport-paas:main
    ports:
      - "84:3000"
    # volumes:
    #   - ./entrypoint.sh:/app/entrypoint.sh:ro
    #   - ./server.js:/app/server.js:ro
    # use .env file
    env_file:
      - .env
  web-debian-2:
    build: 
      context: .
      dockerfile: Dockerfile.debian
    # image: ghcr.io/3kmfi6hp/argo-airport-paas:main
    ports:
      - "85:3000"
    # volumes:
    #   - ./entrypoint.sh:/app/entrypoint.sh:ro
    #   - ./server.js:/app/server.js:ro
    # use .env file
    # env_file:
    #   - .env
